skip_commits:
  files:
    - README.md

image: WMF 5

install:
  - cmd: cinst pester

build: off

test_script:
    - ps: $testResultsFile = ".\TestsResults.xml"
    - ps: $res = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru
    - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
    - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}            